config/routes.rb
Rails.application.routes.draw do

  get 'glossary' => "glossary#index"

  resources :glossary do
    collection do
      get "show_glossary_word"
      get "search"
    end
  end

  get 'account' => "account#index"
  patch 'account/update'

  get 'home' => "home#index"
  get 'lessons_preview' => "home#lessons_preview"
  get 'show_preview_lesson/:id' => "home#show_preview_lesson"
  get 'show_preview_word/:id' => "home#show_preview_word"

  devise_for :users, controllers: { registrations: "registrations" } 

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  resources :poets

  namespace :elearn do
    resources :semesters do
      patch 'activate'
    end
    resources :lessons do
      resources :comments
    end
  end

  resources :poems do
    get "add_audio"
    get "lines"
    resources :stanzas do
      resources :lines do
        patch 'word_references/find'
        resources :word_references
        resources :line_references
      end
    end
  end

  namespace :api , :defaults => { :format => 'json' } do
    namespace :v1 do
      resources :poems, :only => [:show, :index]
      resources :poets, :only => [:show, :index]
      resources :lessons do
        resources :comments
      end
      get 'word_references/find'
      get 'word_references/search'
      get 'word_references/find_all_references'
      resources :word_references , :only => [:show, :index]

    end
  end

  resources :word_references
  resources :lines , :only => [:show]

  namespace :admin do
    resources :users do
      patch 'approve'
      patch 'disapprove'
    end
  end

  get "videos" => "home#videos"
  get "audios" => "home#audios"

  root 'home#index'

end

app/models/semester.rb
class Semester < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  scope :currently_activated , ->() { where(:activated => true).first }  
  STATUSES = {
    1 => "Not Active",
    2 => "Active",    
    3 => "Active In Preview"    
  }

  


end

app/controllers/elearn/base_controller.rb
class Elearn::BaseController < ApplicationController
  before_action :authenticate_user!
#  before_filter :check_redirect


private
  def check_redirect
    if !current_user
      redirect_to home_path , alert: "Only activated user can access the resource"
    end
  end
end

app/controllers/elearn/comments_controller.rb
class Elearn::CommentsController < Elearn::BaseController
  
  def index
    @lesson = Lesson.find(params[:lesson_id])
    @comments = Comment.where(:lesson_id => params[:lesson_id], :semester_id => params[:semester_id])

    render :partial => "comments"
  end
  def new
  end


  def create
    @lesson = Lesson.find(params[:lesson_id])
    @comment = @lesson.comments.new(secured_params)
    @comment.user = current_user 
    @comment.semester = Semester.currently_activated
    respond_to do |format|
      if @comment.save
        format.html { redirect_to [:elearn , @comment.lesson ], notice: 'Comment was successfully added.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lesson = Lesson.find(params[:lesson_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to elearn_lesson_path(@lesson.id), notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def secured_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/elearn/lessons_controller.rb
class Elearn::LessonsController < Elearn::BaseController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all.order("name")#.page(params[:page])
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show  
    @comments = @lesson.comments.current_semester
    @comment = Comment.new
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to [:elearn, @lesson], notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to [:elearn, @lesson], notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.lines.delete_all
    @lesson.comments.delete_all    
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to [:elearn, :lessons], notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :content, :poem_id, :poet_id, :document, :status , :name , :line_ids => [])
    end
end

app/controllers/elearn/semesters_controller.rb
class Elearn::SemestersController <  Elearn::BaseController
  before_action :set_elearn_semester, only: [:show, :edit, :update, :destroy ]

  # GET /elearn/semesters
  # GET /elearn/semesters.json
  def index
    @elearn_semesters = Semester.all.order(:name).page(params[:page])
  end

  # GET /elearn/semesters/1
  # GET /elearn/semesters/1.json
  def show
  end

  # GET /elearn/semesters/new
  def new
    @elearn_semester = Semester.new
  end

  # GET /elearn/semesters/1/edit
  def edit
  end

  # POST /elearn/semesters
  # POST /elearn/semesters.json
  def create
    @elearn_semester = Semester.new(elearn_semester_params)
    @elearn_semester.user = current_user
    respond_to do |format|
      if @elearn_semester.save
        format.html { redirect_to [:elearn, :semesters], notice: 'Semester was successfully created.' }
        format.json { render :show, status: :created, location: @elearn_semester }
      else
        format.html { render :new }
        format.json { render json: @elearn_semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elearn/semesters/1
  # PATCH/PUT /elearn/semesters/1.json
  def update
    respond_to do |format|
      if @elearn_semester.update(elearn_semester_params)
        format.html { redirect_to  [:elearn, :semesters], notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @elearn_semester }
      else
        format.html { render :edit }
        format.json { render json: @elearn_semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elearn/semesters/1
  # DELETE /elearn/semesters/1.json
  def destroy
    @elearn_semester.destroy
    respond_to do |format|
      format.html { redirect_to elearn_semesters_url, notice: 'Semester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
    Semester.update_all(activated: false)

    @semester = Semester.find(params[:semester_id])
    @semester.activated = true
     respond_to do |format|
      if @semester.save()
        format.html { redirect_to  [:elearn, :semesters], notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @elearn_semester }
      else
        format.html { render :edit }
        format.json { render json: @elearn_semester.errors, status: :unprocessable_entity }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elearn_semester
      @elearn_semester = Semester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elearn_semester_params
      params.require(:semester).permit(:name, :user_id, :status, :activated)
    end
end

app/helpers/elearn/comments_helper.rb
module Elearn::CommentsHelper
end

app/helpers/elearn/semesters_helper.rb
module Elearn::SemestersHelper
end

app/views/elearn/semesters/_form.html.erb
<%= form_for(@elearn_semester, :url => [:elearn , @elearn_semester]) do |f| %>
  <% if @elearn_semester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@elearn_semester.errors.count, "error") %> prohibited this elearn_semester from being saved:</h2>

      <ul>
      <% @elearn_semester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="panel panel-primary">
      <div class="panel-heading">Semester Details</div>
      <div class="panel-body">
          <form role="form">
            <div class="form-group">
              <label for="exampleInputEmail1">Name</label>
              <%= f.text_field :name , class: "form-control" , placeholder: "Name"%>                  
            </div>
<!--             <div class="form-group">
              <label for="exampleInputPassword1">Activated</label>
              <%= f.check_box :activated %>
              
            </div> -->
            <%= f.submit  :class => "btn btn-ar btn-primary"%>                
          </form>
      </div>
  </div> <!-- panel panel-primary -->
<% end %>

app/views/elearn/semesters/edit.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">Edit Semester</h1>      
    </div>
</header>

<div class="container">
  <section class="css-section">
    <h2 class="section-title no-margin-top">Edit Learning Semester</h2>
    <%= render "form"%>
  </section>

</div>

app/views/elearn/semesters/index.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">Semesters</h1>

    <% if current_user &&  current_user.has_role?(["lecturer", "admin"]) %>
        <%= link_to 'Add Semester', new_elearn_semester_path, :class => "btn btn-danger pull-right" %>
    <% end %>
        
    </div>
</header>

<div class="container">

  <div class="panel panel-default">
      <div class="panel-heading">
        Available Semesters
      </div>
      <div class="panel-body">
          
          <table class="table table-stripped">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>User</th>      
                <th>Activated</th>
                <th width="20%"></th>
              </tr>
            </thead>

            <tbody>
              <% @elearn_semesters.each_with_index do |elearn_semester , index| %>
                <tr>
                  <td><%= index + 1%></td>
                  <td><%= elearn_semester.name %></td>
                  <td><%= elearn_semester.user.name %></td>
                  <td>
                    <% if elearn_semester.activated %>
                      <button disabled="disabled" class="btn disabled btn-success">Activated</button>
                    <% else %>
                        <%= link_to elearn_semester_activate_path(elearn_semester) , :method => "PATCH" , :class => " btn btn-primary" do %>Activate<% end %>
                    <% end %>
                  </td>
                  <td>
                    <div class="btn-group">                      
                      <%= link_to 'Edit-تعديل', edit_elearn_semester_path(elearn_semester) , class: "btn btn-success" %>
                      <%= link_to 'Destroy', [:elearn ,elearn_semester], method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-success" %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

      </div>
      <div class="panel-footer">
        <section class="text-center">
           <%= paginate @elearn_semesters%>
            
        </section>
      </div> <!-- row -->
      
  </div>
  

</div>

app/views/elearn/semesters/new.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">New Semester</h1>      
    </div>
</header>

<div class="container">
  <section class="css-section">
    <h2 class="section-title no-margin-top">Add New Learning Semester</h2>
    <%= render "form"%>
  </section>


</div>

app/views/elearn/semesters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @elearn_semester.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @elearn_semester.user %>
</p>

<p>
  <strong>Status:</strong>
  <%= @elearn_semester.status %>
</p>

<p>
  <strong>Activated:</strong>
  <%= @elearn_semester.activated %>
</p>

<%= link_to 'Edit-تعديل', edit_elearn_semester_path(@elearn_semester) %> |
<%= link_to 'Back-رجوع', elearn_semesters_path %>