config/routes.rb
Rails.application.routes.draw do

  get 'glossary' => "glossary#index"

  resources :glossary do
    collection do
      get "show_glossary_word"
      get "search"
    end
  end

  get 'account' => "account#index"
  patch 'account/update'

  get 'home' => "home#index"
  get 'lessons_preview' => "home#lessons_preview"
  get 'show_preview_lesson/:id' => "home#show_preview_lesson"
  get 'show_preview_word/:id' => "home#show_preview_word"

  devise_for :users, controllers: { registrations: "registrations" } 

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  resources :poets

  namespace :elearn do
    resources :semesters do
      patch 'activate'
    end
    resources :lessons do
      resources :comments
    end
  end

  resources :poems do
    get "add_audio"
    get "lines"
    resources :stanzas do
      resources :lines do
        patch 'word_references/find'
        resources :word_references
        resources :line_references
      end
    end
  end

  namespace :api , :defaults => { :format => 'json' } do
    namespace :v1 do
      resources :poems, :only => [:show, :index]
      resources :poets, :only => [:show, :index]
      resources :lessons do
        resources :comments
      end
      get 'word_references/find'
      get 'word_references/search'
      get 'word_references/find_all_references'
      resources :word_references , :only => [:show, :index]

    end
  end

  resources :word_references
  resources :lines , :only => [:show]

  namespace :admin do
    resources :users do
      patch 'approve'
      patch 'disapprove'
    end
  end

  get "videos" => "home#videos"
  get "audios" => "home#audios"

  root 'home#index'

end

app/models/stanza.rb
class Stanza < ActiveRecord::Base
  belongs_to :poem
  has_many :lines, dependent: :destroy  
end

app/controllers/stanzas_controller.rb
class StanzasController < BaseSecureController
  #before_action :set_poem, only: [:show, :edit, :update, :destroy]
  def create
    @poem = Poem.find(params[:poem_id])
    @stanza = Stanza.new(:poem => @poem)

    respond_to do |format|
      if @stanza.save
        format.html { redirect_to poem_path(@poem), notice: 'Stanza was successfully created.' }
        format.json { render :show, status: :created, location: @stanza }
      else
        format.html { render :new }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stanza = Stanza.find(params[:id])
    @poem = @stanza.poem
    @stanza.lines.destroy_all
    @stanza.destroy

    #TODO Delete all Words under the stanza
    respond_to do |format|
      format.html { redirect_to poem_path(@poem), notice: 'Stanza and Lines was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:poem_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secure_params
      params.require(:stanza).permit(:poem_id)
    end
end

app/views/stanza/_form.html.erb
          <div class="row contact">
              <%= form_for(@stanza , :url => poem_stanza_index_path(@poem, @stanza)) do |f| %>
                <% if @stanza.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@stanza.errors.count, "error") %> prohibited this stanza from being saved:</h2>

                    <ul>
                    <% @stanza.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
 
                <div class="row submit">                        
                    <div class="span3 right">
                        <%= f.submit %>
                    </div>
                </div>
              
              <% end %>

          </div>

app/views/stanza/edit.html.erb
<h1>Stanza#edit</h1>
<p>Find me in app/views/stanza/edit.html.erb</p>

app/views/stanza/new.html.erb
 <div id="contact">
    <div class="container">
        <div class="section_header">
            <h3>New Stanza</h3>
        </div>
        <%= render 'form' %>
        <div class="pull-right">
          <%= link_to 'رجوع-Back', poems_path , :class => "btn btn-primary"%>
        </div>
    </div>
  </div>


<% content_for :header do %>
  <%= stylesheet_link_tag 'contact' %>
<% end %>

app/views/stanza/show.html.erb
<h1>Stanza#show</h1>
<p>Find me in app/views/stanza/show.html.erb</p>