config/routes.rb
Rails.application.routes.draw do

  get 'glossary' => "glossary#index"

  resources :glossary do
    collection do
      get "show_glossary_word"
      get "search"
    end
  end

  get 'account' => "account#index"
  patch 'account/update'

  get 'home' => "home#index"
  get 'lessons_preview' => "home#lessons_preview"
  get 'show_preview_lesson/:id' => "home#show_preview_lesson"
  get 'show_preview_word/:id' => "home#show_preview_word"

  devise_for :users, controllers: { registrations: "registrations" } 

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  resources :poets

  namespace :elearn do
    resources :semesters do
      patch 'activate'
    end
    resources :lessons do
      resources :comments
    end
  end

  resources :poems do
    get "add_audio"
    get "lines"
    resources :stanzas do
      resources :lines do
        patch 'word_references/find'
        resources :word_references
        resources :line_references
      end
    end
  end

  namespace :api , :defaults => { :format => 'json' } do
    namespace :v1 do
      resources :poems, :only => [:show, :index]
      resources :poets, :only => [:show, :index]
      resources :lessons do
        resources :comments
      end
      get 'word_references/find'
      get 'word_references/search'
      get 'word_references/find_all_references'
      resources :word_references , :only => [:show, :index]

    end
  end

  resources :word_references
  resources :lines , :only => [:show]

  namespace :admin do
    resources :users do
      patch 'approve'
      patch 'disapprove'
    end
  end

  get "videos" => "home#videos"
  get "audios" => "home#audios"

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :omniauthable
  include DeviseTokenAuth::Concerns::User

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  after_create :set_status
  after_create :send_admin_mail

  has_many :comments

  serialize :roles, Array

  before_save -> do
    self.uid = SecureRandom.uuid
  end

  ROLES = {
    1 => "Admin",
    2 => "Lecturer",
    3 => "Student"
  }

  STATUSES = {
    1 => "Active",
    2 => "Not Active"
  }

  def set_status
    if self.has_role?(["admin" , "lecturer"])
     self.approved = 1
     self.save
    end
  end

  def send_admin_mail
    #AdminMailer.new_user_waiting_for_approval(self).deliver
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def is_admin
    if roles.include?(1)
      return true
    else
      return false
    end
  end

  def has_role?( role_array )
    if roles
      if role_array.include?("admin")
        return roles.include?("1")
      end
      if role_array.include?("lecturer")
        return roles.include?("2")
      end
      if role_array.include?("student")
        return roles.include?("3")
      end
    end
    return false
  end



  def role_names
    if roles
      roles.map! do |element|
        if element == "1"
           "Admin"
        elsif element == "2"
           "Lecturer"
        elsif element == "3"
           "Student"
        else
        end
      end
    end
  end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    if params[:approved] == "false"
      @users = User.where(approved: false).order(:email).page(params[:page])
    else
      @users = User.all.order(:email).page(params[:page])
    end

  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(user_params)
    @user.roles

    respond_to do |format|
      if @user.save

        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @user] }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

    # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if user_params[:password].blank?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
    end

    # https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-edit-their-account-without-providing-a-password
    successfully_updated = if needs_password?(@user, user_params)
                             @user.update(user_params)
                           else
                             @user.update_without_password(user_params)
                           end

    respond_to do |format|
      if successfully_updated
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
   # @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  def approve

    @user = User.find(params[:user_id])
    @user.approved = true
     respond_to do |format|
      if @user.save()
        NotifierMailer.approved_notifier(@user).deliver
        format.html { redirect_to  [:admin, :users], notice: 'User was successfully approved.' }
        format.json { render :show, status: :ok, location: [:admin, @user] }
      else
        format.html { render :index }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  def disapprove

    @user = User.find(params[:user_id])
    @user.approved = false
     respond_to do |format|
      if @user.save()
        NotifierMailer.disapproved_notifier(@user).deliver
        format.html { redirect_to  [:admin, :users], notice: 'User was successfully approved.' }
        format.json { render :show, status: :ok, location: [:admin, @user] }
      else
        format.html { render :index }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation , :status_id , [roles:  []] , :name )
    end

    def needs_password?(user, params)
      params[:password].present?
    end
end

app/views/admin/users/_form.html.erb
<%= form_for(@user , :url => [:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="panel panel-primary">
      <div class="panel-heading">User Details</div>
      <div class="panel-body">
          
            <div class="form-group">
              <label for="exampleInputEmail1">Name</label>
              <%= f.text_field :name , class: "form-control" , placeholder: "Name"%>                  
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Email</label>
              <%= f.email_field :email , class: "form-control" , placeholder: "Password"%>                  
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Password</label>
              <%= f.password_field :password , class: "form-control" , placeholder: "Password"%>                  
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Roles</label>
              <%= f.collection_select :roles, User::ROLES,:first,:last, {include_blank: false },  {:required => true, :multiple => true , :class=> "form-control"}%> 
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Status</label>
                <%= f.collection_select :status_id, User::STATUSES ,:first,:last,{},  {:required => true,:class=> "form-control"}%> 
            </div>
            
            <%= f.submit "Save", :class => "btn btn-ar btn-primary"%> 
            <%= link_to 'Cancel', admin_users_path, :class => "btn btn-danger" %> 

          
      </div>
  </div> <!-- panel panel-primary -->
<% end %>

app/views/admin/users/edit.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">Edit User</h1>      
    </div>
</header>

<div class="container">
  <section class="css-section">
    
    <%= render "form"%>
  </section>

</div>

app/views/admin/users/index.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">Users</h1>

    <% if current_user &&  current_user.has_role?(["admin"]) %>
        <%= link_to 'Add User', new_admin_user_path, :class => "btn btn-danger pull-right" %>
        
    <% end %>
        
    </div>
</header>

<div class="container">

  <div class="panel panel-default">
      <div class="panel-heading">
        Available Users
      </div>
      <div class="panel-body">
          
          <table class="table table-stripped">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Approved</th>
                <th width="30%"></th>
              </tr>
            </thead>

            <tbody>
             <% @users.each_with_index do |user , index| %>
                <tr>
                  <td><%= index + 1%></td>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.role_names %></td>
                  <td>
                    <% if user.approved%>
                    Yes
                    <%else%>
                    No
                    <%end%>
                  </td>
                  <td>
                    <div class="btn-group">                        
                      <% if user.approved %>
                        <!-- <button disabled="disabled" class="btn disabled btn-success">Approved</button> -->
                        <% if user != current_user%>
                              <%= link_to admin_user_disapprove_path(user) , :method => "PATCH" , :class => " btn btn-success" do %>Disapprove<% end %>
                        <% end %>
                      <% else %>
                          <%= link_to admin_user_approve_path(user) , :method => "PATCH" , :class => " btn btn-primary" do %>Approve<% end %>
                      <% end %>
                      <% link_to 'Show', [:admin, user] , :class => "btn btn-warning" %>
                      <%= link_to 'Edit-تعديل', edit_admin_user_path(user) , :class => "btn btn-warning" %>
                      <% link_to 'Delete', [:admin, user], method: :delete, data: { confirm: 'Are you sure?' }  , :class => "btn btn-warning"%>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

      </div>
      <div class="panel-footer">
        <section class="text-center">
          <%= paginate @users %>     
        </section>
      </div> <!-- row -->
      
      
  </div>
</div>
  

app/views/admin/users/new.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">New User</h1>      
    </div>
</header>

<div class="container">
  <section class="css-section">
    <h2 class="section-title no-margin-top">New Login User</h2>
    <%= render "form"%>
  </section>

</div>

app/views/admin/users/show.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">User Details</h1>

        <ol class="breadcrumb pull-right">
            <li><a href="#">Main</a></li>
            <li class="active">User Details</li>
        </ol>
    </div>
</header>
<div class="container">

    <p>
      <strong>Name: </strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email: </strong>
      <%= @user.email %>
    </p>
    <p>
      <strong>Roles: </strong>
      <%= @user.role_names %>
    </p>

    <div class="btn-group">
      <%= link_to 'Edit-تعديل', edit_admin_user_path(@user) , class: "btn btn-warning" %> 
      <%= link_to 'Back-رجوع', admin_users_path , class: "btn btn-warning"%>
    </div>
    <br> <br> 
</div>