config/routes.rb
Rails.application.routes.draw do

  get 'glossary' => "glossary#index"

  resources :glossary do
    collection do
      get "show_glossary_word"
      get "search"
    end
  end

  get 'account' => "account#index"
  patch 'account/update'

  get 'home' => "home#index"
  get 'lessons_preview' => "home#lessons_preview"
  get 'show_preview_lesson/:id' => "home#show_preview_lesson"
  get 'show_preview_word/:id' => "home#show_preview_word"

  devise_for :users, controllers: { registrations: "registrations" } 

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  resources :poets

  namespace :elearn do
    resources :semesters do
      patch 'activate'
    end
    resources :lessons do
      resources :comments
    end
  end

  resources :poems do
    get "add_audio"
    get "lines"
    resources :stanzas do
      resources :lines do
        patch 'word_references/find'
        resources :word_references
        resources :line_references
      end
    end
  end

  namespace :api , :defaults => { :format => 'json' } do
    namespace :v1 do
      resources :poems, :only => [:show, :index]
      resources :poets, :only => [:show, :index]
      resources :lessons do
        resources :comments
      end
      get 'word_references/find'
      get 'word_references/search'
      get 'word_references/find_all_references'
      resources :word_references , :only => [:show, :index]

    end
  end

  resources :word_references
  resources :lines , :only => [:show]

  namespace :admin do
    resources :users do
      patch 'approve'
      patch 'disapprove'
    end
  end

  get "videos" => "home#videos"
  get "audios" => "home#audios"

  root 'home#index'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :poem
  belongs_to :poet
  has_many :comments

  has_many :poem_lines, foreign_key: "lesson_id", class_name: LessonLine 
  has_many :lines , class_name: Line , through: :poem_lines 
  

  scope :previews , ->() { where(:status => 3) }

  STATUSES = {
    2 => "Active",    
    3 => "Active In Preview",    
    1 => "Not Active"
    
  }

  
  def status_text
    case self.status
      when 1
        "Not Active"
      when 2
        "Active"
      when 3
        "Active In Preview"
      end
  end

end

app/controllers/api/v1/lessons_controller.rb
class Api::V1::LessonsController < Api::V1::BaseController

  # GET /api/v1/Lessons
  # GET /api/v1/Lessons.json
  def index

    if user_signed_in?  
      @lessons = Lesson.all.order(:name)
    else
      @lessons = Lesson.previews
    end
  end


  # GET /api/v1/Lessons/1
  # GET /api/v1/Lessons/1.json
  def show
    
    #if user_signed_in?  
      @lesson = Lesson.find(params[:id])    
    #else
    #  @lesson = Lesson.previews.where(:id => params[:id]).first
    #end
  end

end

app/controllers/elearn/base_controller.rb
class Elearn::BaseController < ApplicationController
  before_action :authenticate_user!
#  before_filter :check_redirect


private
  def check_redirect
    if !current_user
      redirect_to home_path , alert: "Only activated user can access the resource"
    end
  end
end

app/controllers/elearn/comments_controller.rb
class Elearn::CommentsController < Elearn::BaseController
  
  def index
    @lesson = Lesson.find(params[:lesson_id])
    @comments = Comment.where(:lesson_id => params[:lesson_id], :semester_id => params[:semester_id])

    render :partial => "comments"
  end
  def new
  end


  def create
    @lesson = Lesson.find(params[:lesson_id])
    @comment = @lesson.comments.new(secured_params)
    @comment.user = current_user 
    @comment.semester = Semester.currently_activated
    respond_to do |format|
      if @comment.save
        format.html { redirect_to [:elearn , @comment.lesson ], notice: 'Comment was successfully added.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lesson = Lesson.find(params[:lesson_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to elearn_lesson_path(@lesson.id), notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def secured_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/elearn/lessons_controller.rb
class Elearn::LessonsController < Elearn::BaseController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all.order("name")#.page(params[:page])
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show  
    @comments = @lesson.comments.current_semester
    @comment = Comment.new
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to [:elearn, @lesson], notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to [:elearn, @lesson], notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.lines.delete_all
    @lesson.comments.delete_all    
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to [:elearn, :lessons], notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :content, :poem_id, :poet_id, :document, :status , :name , :line_ids => [])
    end
end

app/controllers/elearn/semesters_controller.rb
class Elearn::SemestersController <  Elearn::BaseController
  before_action :set_elearn_semester, only: [:show, :edit, :update, :destroy ]

  # GET /elearn/semesters
  # GET /elearn/semesters.json
  def index
    @elearn_semesters = Semester.all.order(:name).page(params[:page])
  end

  # GET /elearn/semesters/1
  # GET /elearn/semesters/1.json
  def show
  end

  # GET /elearn/semesters/new
  def new
    @elearn_semester = Semester.new
  end

  # GET /elearn/semesters/1/edit
  def edit
  end

  # POST /elearn/semesters
  # POST /elearn/semesters.json
  def create
    @elearn_semester = Semester.new(elearn_semester_params)
    @elearn_semester.user = current_user
    respond_to do |format|
      if @elearn_semester.save
        format.html { redirect_to [:elearn, :semesters], notice: 'Semester was successfully created.' }
        format.json { render :show, status: :created, location: @elearn_semester }
      else
        format.html { render :new }
        format.json { render json: @elearn_semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elearn/semesters/1
  # PATCH/PUT /elearn/semesters/1.json
  def update
    respond_to do |format|
      if @elearn_semester.update(elearn_semester_params)
        format.html { redirect_to  [:elearn, :semesters], notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @elearn_semester }
      else
        format.html { render :edit }
        format.json { render json: @elearn_semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elearn/semesters/1
  # DELETE /elearn/semesters/1.json
  def destroy
    @elearn_semester.destroy
    respond_to do |format|
      format.html { redirect_to elearn_semesters_url, notice: 'Semester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
    Semester.update_all(activated: false)

    @semester = Semester.find(params[:semester_id])
    @semester.activated = true
     respond_to do |format|
      if @semester.save()
        format.html { redirect_to  [:elearn, :semesters], notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @elearn_semester }
      else
        format.html { render :edit }
        format.json { render json: @elearn_semester.errors, status: :unprocessable_entity }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elearn_semester
      @elearn_semester = Semester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elearn_semester_params
      params.require(:semester).permit(:name, :user_id, :status, :activated)
    end
end

app/helpers/elearn/comments_helper.rb
module Elearn::CommentsHelper
end

app/helpers/elearn/semesters_helper.rb
module Elearn::SemestersHelper
end

app/views/elearn/lessons/_form.html.erb
  <%= form_for([:elearn,@lesson], :class=>"form-inline" ) do |f| %>
    <% if @lesson.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

        <ul>
        <% @lesson.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>



    <div class="panel panel-primary">
        <div class="panel-heading">Lesson Details</div>
        <div class="panel-body">
            
              <div class="form-group">
                <label for="exampleInputEmail1">Title *</label>
                <%= f.text_field :title , class: "form-control" , placeholder: "Title" , required: true , :dir => "rtl" , :lang => "ar"%>                  
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Lesson Name *</label>
                <%= f.text_field :name , class: "form-control" , placeholder: "Lesson Name", required: true%>                  
              </div>            
              <hr class="dotted">
              <div class="form-group">
                <label for="exampleInputPassword1">Content (If not Poem or Poet)</label>
                <%= f.cktext_area :content , :class => "form-control" %>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Poem</label>
                <%= f.collection_select :poem_id, Poem.all,:id,:title, { :include_blank => "Select poem"} , {:class => "form-control"}%>       
              </div>

              <div class="form-group">
                <label for="exampleInputPassword1">Lines</label>
                <%= f.collection_select :line_ids, @lesson.lines,:id,:text, {} , {:class => "form-control"  , multiple: true}%>       
              </div>

              <div class="form-group">
                <label for="exampleInputPassword1">Poet</label>
                <%= f.collection_select :poet_id, Poet.all,:id,:name, { prompt: "Select Poet" } , { :class => "form-control"}%>       
              </div>
              <hr class="dotted">
              <div class="form-group">
                <label for="exampleInputPassword1">Status</label>
                  <%= f.collection_select :status, Lesson::STATUSES,:first,:last, {}, { :class => "form-control"} %> 
              </div>
              <%= f.submit "Save", :class  => "btn btn-ar btn-primary"%>                
              <%= link_to 'Cancel', elearn_lessons_path, :class => "btn btn-danger" %>
        </div>
    </div> <!-- panel panel-primary -->

  <% end %>

<% content_for :header do %> 
  <%= javascript_include_tag 'poem' %>
<% end %>

app/views/elearn/lessons/_poem.html.erb
<section>

    <!-- <img src="assets/img/demo/7.jpg" class="img-responsive imageborder" alt="Image"> -->
    <% if @lesson.poem %>
      <h2 class="page-header no-margin-top" >
        <div class="row">
          <div class="col-md-6"><%= (audio_tag @lesson.poem.audio, :controls => true) if @lesson.poem.audio_url %>    
          </div>
          <div class="col-md-6" dir="rtl">
            <%= @lesson.poem.title%>
          </div>
        </div>
      </h2>
    
      <% @lesson.poem.stanzas.each do | stanza | %>
          <% if @lesson.lines.length > 0 %>
            <% lines = @lesson.lines %>
          <% else %>
            <% lines = stanza.lines %>
          <% end %>
          <div class=" stanza">              
                          
            <div class="poem-stanza-lines" data-id="<%= stanza.id %>">
              <table class="table table-striped" >     
              <% lines.each_with_index do | line , index|%>
                
                  <tr>
                    <td>                                   
                        <div class='<%= "poem-stanza" %>' 
                          data-line-id="<%= line.id %>"  
                          data-poem-id="<%= @lesson.poem.id %>"  
                          data-stanza-id="<%= stanza.id %>"  
                          style="font-size:20px;  text-align: center; " >                                                                  
                            <% line.splitted_text.each_with_index do | word ,index|  %> 
                              <% if line.word_references.word_indexes_filtered(index).count > 0  %>                              
                                <span class="<%= current_user ? "poem-stanza-line-word" : "poem-stanza-line-info" %>  word-" data-word-index="<%= index %>" 

                                  style="color:green;  cursor:pointer;"
                                  >
                                  <%= word %>              
                                </span>  
                              <% else %>
                                <span data-word-index="<%= index %>">
                                  <%= word %>              
                                </span>  
                              <% end %>
                            <% end %>     

                        </div>
                        <% if line.line_references.length > 0 %>
                            <div class="pull-right" style="margin-top:-27px">
                              <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%=index%>" aria-expanded="false" class="collapsed">
                                  <i class="fa fa-chevron-left" aria-hidden="true"></i>
                              </a>                          
                            </div>                            
                        
                              <div id="collapse<%=index%>" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                <div class="panel-body">
                                  <div>
                                    <ul class="nav nav-tabs nav-tabs-ar nav-tabs-ar-white">
                                      <% line.line_references.order(:reference_type).each_with_index do | line_ref , index_j |%>
                                        <li class="<%= 'active' if index_j == 0 %>">
                                          <a href="#tab<%= "#{index}#{index_j}"%>" data-toggle="tab" aria-expanded="false">
                                          <%= line_ref.reference_type_text %></a>
                                        </li>                                    
                                      <% end %>
                                      <% if @lesson.poem.word_references.with_line(line.id).grammars.length > 0 %>
                                        <li >
                                          <a href="#tabgrammer<%= "#{index}"%>" data-toggle="tab" aria-expanded="false">
                                          الإعراب</a>
                                        </li>                                    
                                      <% end %>
                                      <% if @lesson.poem.word_references.with_line(line.id).words.length > 0 %>
                                        <li >
                                          <a href="#tabwords<%= "#{index}"%>" data-toggle="tab" aria-expanded="false">
                                          المفردات</a>
                                        </li>                                    
                                      <% end %>
                                    </ul>
                                    <div class="tab-content">
                                      <% line.line_references.order(:reference_type).each_with_index do | line_ref , index_j |%> 
                                        
                                          <div class="tab-pane <%= 'active' if index_j == 0 %>" id="tab<%= "#{index}#{index_j}"%>" dir="rtl" lang="ar">
                                            <% if line_ref.reference_type == 4 %>
                                              <%= audio_tag line_ref.media , :controls => true%>
                                            <% elsif line_ref.reference_type == 5  %>
                                              <%= image_tag line_ref.media , width: "100%" %>
                                            <% elsif line_ref.reference_type == 6 %>
                                              <%= video_tag line_ref.media , controls: true , width: "100%" %>
                                            <% else %>  
                                              <%= raw line_ref.content %>                                            
                                            <% end %>                                        
                                          </div>                                      
                                        
                                      <% end %>
                                      <% if @lesson.poem.word_references.with_line(line.id).grammars.length > 0 %>
                                        <div class="tab-pane" id="tabgrammer<%= "#{index}"%>" dir="rtl" lang="ar">
                                          <table class="table table-condensed" dir="rtl" >                    
                                              <% @lesson.poem.word_references.with_line(line.id).grammars.each do |word_ref| %>
                                                  <tr>                                                      
                                                      <td><%= word_ref.word %> </td><td ><span dir="rtl" style="float:right;"> <%= word_ref.description %></span></td>
                                                  </tr>
                                              <% end %>                        
                                          </table>            
                                            
                                        </div>                                        
                                      <% end %>
                                      <% if @lesson.poem.word_references.with_line(line.id).words.length > 0 %>
                                        <div class="tab-pane" id="tabwords<%= "#{index}"%>" dir="rtl" lang="ar">
                                          <table class="table table-condensed" dir="rtl" >                    
                                              <% @lesson.poem.word_references.with_line(line.id).words.each do |word_ref| %>
                                                  <tr>                                                      
                                                      <td><%= word_ref.word %> </td>
                                                      <td><span dir="rtl" style="float:right;"> <%= word_ref.description %></span></td>
                                                  </tr>
                                              <% end %>                        
                                          </table>            
                                            
                                        </div>                                        
                                      <% end %>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            
                          </div>
                          
                        <% end %>  
                    </td>
                    <td class="">
                      <div class="pull-left">
                        
                      </div>
                    </td>
                  </tr>                          
                
              <% end %>
              </table>
            </div><br>
              
          </div><br>
      <% end %>            
    <% end %>
</section>

app/views/elearn/lessons/_poet.html.erb
<div class="panel panel-primary">
    <div class="panel-heading"><i class="fa fa-comments"></i> Poet</div>
    <div class="panel-body">
        <% if @lesson.poet %>
          
          <div><center><h3><%= @lesson.poet.name%></h3></center></div>
          <div class="pull-left "><%= (audio_tag @lesson.poet.media, :controls => true) if @lesson.poet.media_url %></div>
          <div class="readmore" dir="rtl" >
            <%= @lesson.poet.biography.html_safe%>
          </div>  
        
        <% end %>
    </div>
</div>

app/views/elearn/lessons/edit.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">Edit Lesson</h1>      
    </div>
</header>

<div class="container">
  <section class="css-section">
    <h2 class="section-title no-margin-top">Edit-تعديل <%= @lesson.title%></h2>
    <%= render "form"%>
  </section>


</div>

app/views/elearn/lessons/index.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">دروس-Lessons</h1>

    <% if current_user &&  current_user.has_role?(["lecturer", "admin"]) %>
        <%= link_to 'Add Lesson-إضافة درس', new_elearn_lesson_path, :class => "btn btn-danger pull-right" %>
    <% end %>
        
    </div>
</header>
<div class="container">

    <% if current_user &&  !current_user.has_role?(["student"]) %>
    <!--     <h4>*This is only Preview, Please "SIGN IN" for Full View Setting.</h4> -->
    <% end %>

    <div class="row">

        <div class="col-xs-12">
    
            <% @lessons.each do |lesson| %>
                <article class="post animated fadeInDown animation-delay-6">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="post-title">                                
                                <a href="<%= elearn_lesson_path(lesson) %>" class="transicion">
                                    <%= lesson.name %> &nbsp;
                                                   
                                <span class="pull-right" dir="rtl" lang="ar"><%= lesson.title %></span>
                                </a>             
                            </h3>
                            
                                <div  dir="rtl" >
                                    <table class="table table-striped">
                                        <tr>
                                            <% if lesson.poem %>
                                                <td min-width="20%">                                                    
                                                    <h4><%= lesson.poem.title %></h4>
                                                </td>
                                            <% end %>
                                            <% if lesson.poet %>
                                                <td>                                                
                                                    <h4><%= lesson.poet.name %></h4>
                                                
                                                </td>
                                            <% end %>                                            
                                        </tr>
                                        <tr>
                                            
                                            
                                            <td style="vertical-align: middle;" colspan="100%">
                                                <% if lesson.content %>
                                                
                                                    <div class="readmore" dir="rtl" >
                                                        <%= lesson.content.html_safe %>
                                                    </div>                                                
                                                
                                            <% end %>
                                                <div class="pull-left">
                                                <% if current_user &&  current_user.has_role?(["lecturer", "admin"]) %>
                                                    <%= link_to 'Delete', [:elearn, lesson], method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-ar btn-danger pull- btn-xs" %>
                                                    <%= link_to 'Edit-تعديل', edit_elearn_lesson_path(lesson) , class: "btn btn-ar btn-warning pull- btn-xs" %>
                                                <% end %>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            
                        </div>
                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-lg-10 col-md-9 col-sm-4">
                                    <i class="fa fa-clock-o"></i> <%= lesson.updated_at%> 
                                    <% if lesson.poet%>
                                    <i class="fa fa-user"> </i> 
                                    <a href="#"><%= lesson.poet.name%></a> 
                                    <% end %>
                                    
                                </div>
                                <div class="col-lg-2 col-md-3 col-sm-4">
                                    <% if current_user %>                                      
                                        <%= link_to [:elearn , lesson] , class: "pull-right" do %> Show &raquo;<% end %>
                                    <% else %>                        
                                        <%= link_to "show_preview_lesson/#{lesson.id}", class: " pull-right" do %>Show &raquo;<% end %>
                                    <% end %>  
                                </div>
                            </div>
                        </div>
                    </div>
                </article>                
            <% end %>
                
            
            <section>
                <%%>
            </section>
        </div> <!-- col-md-8 -->

    </div> <!-- row -->
</div>

app/views/elearn/lessons/new.html.erb
<header class="main-header">
    <div class="container">
        <h1 class="page-title">Add New Lesson</h1>      
    </div>
</header>

<div class="container">
  <section class="css-section">
    <h2 class="section-title no-margin-top">Add New Lesson For Students</h2>
    <%= render "form"%>
  </section>


</div>

app/views/elearn/lessons/show.html.erb
<header class="main-header">
    <div class="container">
        
        <span class="pull">
            <% if current_user %>
            <%= link_to 'Back-رجوع', elearn_lessons_path, :class => "btn btn-danger " %>
            <% else %>
                <%= link_to 'Home-صفحة رئيسة', root_path, :class => "btn btn-danger " %>
            <% end %>
        </span>
        <!--<h1 class="page-title"> </h1>

       <ol class="breadcrumb pull-right">
            <li><a href="#">Main</a></li>
            <li><a href="#">Lessons-دروس</a></li>
            <li class="active"><%= @lesson.name %></li>
        </ol> -->

        <h1 class="page-title pull-right"><%= "#{@lesson.title}" if @lesson.title %></h1><br>
        <h4 class="page-title pull-right"><font size="4"><%= "#{@lesson.name}" %></font></h4>
        
    </div>
</header>
<div class="container">
    <div class="row">
        <% if @lesson.poet %>
            <div class="
            <% if @lesson.poem %>
            col-md-4
            <% else %>
            col-md-12
            <% end %>
            ">
                <aside class="sidebar">
                    
                    <%= render "elearn/lessons/poet"%>
                    
                </aside> <!-- Sidebar -->
            </div>
        <% end %>

        <div class="
            <% if @lesson.poet && @lesson.poem %>
                col-md-8
            <% else %>
                col-md-12
            <% end %>">
            <% if @lesson.poem %>
                <%= render "elearn/lessons/poem"%>
            <% end %>
            <% if @lesson.content != "" %>

                <section>
                    <div class="panel panel-default">
                        <div class="panel-body">
                                <%= raw @lesson.content %>
                        </div>
                    </div>                    
                </section>
                
            <% end %>
            <% if current_user %>
                 <h2 class="section-title">
                    <div class="row">
                        <div class="col-md-8">
                            Comments 
                        </div>
                        <div class="col-md-4" style="font-size:15px">
                            <% if current_user.has_role?(["admin" , "lecturer"])%>
                                <%= collection_select(:semester, :semester_id, Semester.all, :id, :name, 
                                {
                                    :prompt => "Show comments in semester",selected: Semester.currently_activated.id
                                }, 
                                {
                                    :class => "form-control" , 
                                    :id => "select_semester" , 
                                    "data-lesson-id" => @lesson.id
                                } )%>
                            <% end %>
                        </div>

                    </div>
                </h2>
                <%= render  "elearn/comments/comments" %>              
                <%= render  "elearn/comments/new_comment" %>     
            <% end %>
            <br /><br />
        </div>
    </div>
</div>
<% content_for :header do %> 
  <%= javascript_include_tag 'lesson' %>
<% end %>